import type { AgendaEvent } from "./types";

export const agenda: AgendaEvent[] = [
  {
    date: "2026-09-01",
    time: "09:00",
    indicator: "PIB trimestral (IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Indica o ritmo de crescimento da economia e pode influenciar as projeções do Copom",
      "Resultado forte tende a sustentar juros elevados e pressionar o câmbio",
      "Mobiliza expectativas de arrecadação e cenário fiscal",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-01",
    time: "10:00",
    indicator: "Leilão de títulos públicos (Tesouro Nacional)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "A demanda dos investidores sinaliza apetite por prazos e indexadores",
      "As taxas praticadas orientam a precificação da renda fixa privada",
      "Resultados fracos podem indicar exigência de prêmio maior",
    ],
    source: "Tesouro Nacional",
    sourceUrl: "https://www.gov.br/tesouronacional",
  },
  {
    date: "2026-09-01",
    time: "15:00",
    indicator: "Balança comercial (MDIC)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "O saldo comercial é um dos vetores da oferta de moeda estrangeira",
      "Superávit maior tende a favorecer o real; déficit pressiona o câmbio",
      "Relevante para clientes que importam ou exportam",
    ],
    source: "Ministério do Desenvolvimento, Indústria, Comércio e Serviços",
    sourceUrl: "https://www.gov.br/mdic",
  },
  {
    date: "2026-09-02",
    time: "09:00",
    indicator: "Produção industrial (PIM-PF, IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Retrata a atividade industrial e o dinamismo da economia",
      "Alimenta projeções de crescimento do PIB",
      "Indústria fraca pode reduzir a pressão inflacionária de bens industriais",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-02",
    time: "18:30",
    indicator: "Reunião do Copom (decisão da Selic)",
    expectation: null,
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "A Selic define o custo do crédito e a referência da renda fixa",
      "Mudança na taxa impacta preços de títulos e fundos de renda fixa",
      "A decisão influencia inflação, câmbio e expectativas de mercado",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-04",
    time: "09:30",
    indicator: "Payroll americano (BLS)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Gerações de empregos nos EUA orientam as decisões do Fed",
      "Mercado de trabalho forte pode adiar cortes de juros americanos",
      "Impacta juros dos Treasuries, o dólar e os fluxos para emergentes",
    ],
    source: "U.S. Bureau of Labor Statistics (BLS)",
    sourceUrl: "https://www.bls.gov/",
  },
  {
    date: "2026-09-08",
    time: "08:00",
    indicator: "Ata da reunião do Copom",
    expectation: null,
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Detalha os argumentos da decisão e sinaliza os próximos passos da Selic",
      "O tom do documento mexe com as apostas de juros futuros",
      "Ajuda a calibrar prazos e indexadores da renda fixa",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-08",
    time: "08:25",
    indicator: "Relatório Focus (BCB)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Medianas das expectativas de Selic, inflação e câmbio",
      "Direção das projeções orienta decisões de prazo em investimentos",
      "Desancoragem de expectativas costuma pressionar os juros longos",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-08",
    time: "10:00",
    indicator: "Leilão de títulos públicos (Tesouro Nacional)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Demanda e taxas dos títulos refletem o apetite por risco de mercado",
      "Prestação de referências para CDBs, LCIs e LCAs",
      "Sinaliza a inclinação da curva de juros",
    ],
    source: "Tesouro Nacional",
    sourceUrl: "https://www.gov.br/tesouronacional",
  },
  {
    date: "2026-09-09",
    time: "09:00",
    indicator: "IPCA (IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Inflação oficial do país, referência da meta e da política monetária",
      "Acima do esperado tende a manter ou elevar os juros",
      "Ancora o rendimento real dos títulos IPCA+",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-11",
    time: "09:30",
    indicator: "CPI americano (BLS)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Inflação dos EUA orienta as decisões do Fed sobre juros",
      "Muda o prêmio dos Treasuries e a força do dólar",
      "Dólar mais forte tende a pressionar o real e os ativos locais",
    ],
    source: "U.S. Bureau of Labor Statistics (BLS)",
    sourceUrl: "https://www.bls.gov/",
  },
  {
    date: "2026-09-14",
    time: "08:25",
    indicator: "Relatório Focus (BCB)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Atualiza expectativas de mercado para Selic e inflação",
      "Mudanças nas projeções mexem com a curva de juros",
      "Orienta o comparativo entre títulos prefixados e IPCA+",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-14",
    time: "09:00",
    indicator: "Setor de serviços (PMS, IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Serviços são o maior setor da economia e respondem por boa parte da inflação",
      "Indica a força do consumo das famílias",
      "Alimenta as projeções de atividade e PIB",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-15",
    time: "09:00",
    indicator: "IPCA-15 (IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Prévia mensal do IPCA e antecipa a tendência da inflação oficial",
      "Surpresa inflacionária mexe com juros futuros e renda fixa",
      "Referência para decisões de hedge contra inflação",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-15",
    time: "09:30",
    indicator: "PPI americano (BLS)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Preços ao produtor dos EUA antecipam pressões sobre a inflação ao consumidor",
      "Influencia as apostas para o FOMC e os juros americanos",
      "Transborda para o câmbio e os ativos de mercados emergentes",
    ],
    source: "U.S. Bureau of Labor Statistics (BLS)",
    sourceUrl: "https://www.bls.gov/",
  },
  {
    date: "2026-09-16",
    time: "09:00",
    indicator: "Varejo ampliado (PMC, IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Mede o consumo das famílias e o efeito dos juros sobre a demanda",
      "Varejo fraco indica arrefecimento da economia e da inflação",
      "Sinaliza o ambiente para o crédito ao consumo",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-16",
    time: "15:00",
    indicator: "Reunião do FOMC (decisão de juros dos EUA)",
    expectation: null,
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Juros americanos influenciam o dólar, o real e o fluxo para emergentes",
      "Comunicação do Fed orienta o prêmio de risco dos ativos globais",
      "Impacta fundos e investimentos com exposição internacional",
    ],
    source: "Federal Reserve (Fed)",
    sourceUrl: "https://www.federalreserve.gov/",
  },
  {
    date: "2026-09-17",
    time: "09:00",
    indicator: "IBC-Br (BCB)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Prévia mensal da atividade econômica acompanhada pelo Copom",
      "Indica o ritmo da economia entre os PIBs trimestrais",
      "Influencia projeções de crescimento e a trajetória dos juros",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-21",
    time: "08:25",
    indicator: "Relatório Focus (BCB)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Atualiza o consenso de mercado para as principais variáveis",
      "Desvio nas projeções de inflação tende a alterar os juros futuros",
      "Referência para conversas sobre prazos da renda fixa",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-22",
    time: "10:00",
    indicator: "Leilão de títulos públicos (Tesouro Nacional)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "As taxas aceitas no leilão ancoram a precificação da renda fixa",
      "Demanda forte por títulos longos reduz o prêmio de prazo",
      "Sinaliza a percepção de risco fiscal do mercado",
    ],
    source: "Tesouro Nacional",
    sourceUrl: "https://www.gov.br/tesouronacional",
  },
  {
    date: "2026-09-24",
    time: "09:00",
    indicator: "PNAD Contínua (taxa de desemprego, IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Mercado de trabalho aquecido sustenta consumo, mas pode pressionar serviços e inflação",
      "Desemprego alto enfraquece a demanda e favorece a inflação baixa",
      "Orienta a análise de capacidade de pagamento e risco de crédito",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-25",
    time: "09:30",
    indicator: "PCE americano (BEA)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Medida de inflação preferida pelo Fed para calibrar os juros",
      "Números pressionam as apostas sobre o próximo FOMC",
      "Afeta o dólar, os juros americanos e o fluxo para o Brasil",
    ],
    source: "U.S. Bureau of Economic Analysis (BEA)",
    sourceUrl: "https://www.bea.gov/",
  },
  {
    date: "2026-09-28",
    time: "08:25",
    indicator: "Relatório Focus (BCB)",
    expectation: null,
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Consolida as expectativas do mercado na véspera da reunião do Copom",
      "Projeções para a Selic ganham relevância no fim do ciclo de divulgações",
      "Referência para calibrar propostas de renda fixa aos clientes",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-28",
    time: "09:00",
    indicator: "Operações de crédito do SFN (BCB)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Mostra a expansão do crédito, as taxas médias e a inadimplência",
      "Crédito mais caro ou inadimplência em alta tende a restringir concessões",
      "Contexto importante para conversas sobre financiamentos",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
  {
    date: "2026-09-29",
    time: "08:00",
    indicator: "IGP-M (FGV)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Reajusta aluguéis e contratos indexados, afetando o orçamento de clientes",
      "Peso de commodities e custos antecipa pressões inflacionárias",
      "Impacta títulos e fundos atrelados ao índice",
    ],
    source: "FGV",
    sourceUrl: "https://portal.fgv.br/",
  },
  {
    date: "2026-09-29",
    time: "09:00",
    indicator: "IPP (IBGE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Preços ao produtor da indústria antecipam a inflação ao consumidor",
      "Variação no custo de insumos pode chegar aos preços finais",
      "Sinaliza pressões de custo em setores específicos",
    ],
    source: "IBGE",
    sourceUrl: "https://www.ibge.gov.br/",
  },
  {
    date: "2026-09-30",
    time: "15:00",
    indicator: "CAGED (empregos formais, MTE)",
    expectation: "depende da divulgação oficial",
    previous: null,
    importance: "media",
    timezone: "Brasília",
    impactos: [
      "Geração de empregos formais reflete a saúde do mercado de trabalho",
      "Emprego em alta sustenta consumo e arrecadação",
      "Complementa a leitura da PNAD Contínua",
    ],
    source: "Ministério do Trabalho e Emprego",
    sourceUrl: "https://www.gov.br/trabalho-e-emprego",
  },
  {
    date: "2026-09-30",
    time: "18:30",
    indicator: "Reunião do Copom (decisão da Selic)",
    expectation: null,
    previous: null,
    importance: "alta",
    timezone: "Brasília",
    impactos: [
      "Encerra o ciclo de decisões do mês e define o rumo da Selic",
      "A decisão impacta taxas de financiamento e o rendimento da renda fixa",
      "Reage no câmbio, na bolsa e nas projeções de inflação",
    ],
    source: "Banco Central do Brasil",
    sourceUrl: "https://www.bcb.gov.br/",
  },
];
